"""Add profile fields to User model

Revision ID: 0ed7caca83f0
Revises: bee70452f0ca
Create Date: 2025-04-13 13:47:28.470289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ed7caca83f0'
down_revision = 'bee70452f0ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.drop_index('phone')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', mysql.VARCHAR(length=120), nullable=False))
        batch_op.create_index('phone', ['phone'], unique=True)
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('company_name')
        batch_op.drop_column('position')
        batch_op.drop_column('bio')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
