"""Add uploaded_by to File model

Revision ID: 4799ddaf4177
Revises: d9cfc7e4db2e
Create Date: 2025-06-27 01:07:38.391618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4799ddaf4177'
down_revision = 'd9cfc7e4db2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('file_size')

    # ### end Alembic commands ###
