"""Add ON DELETE CASCADE to user_id in verifications and user_preferences

Revision ID: 53e0976f6d45
Revises: 71078d4ab723
Create Date: 2025-06-13 18:02:48.504355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53e0976f6d45'
down_revision = '71078d4ab723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_constraint('user_preferences_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_preferences_ibfk_1', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
