"""modified task.py

Revision ID: 57747f63a2d9
Revises: ea288ca68e1d
Create Date: 2025-06-04 18:12:41.447407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57747f63a2d9'
down_revision = 'ea288ca68e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('read_at')

    # ### end Alembic commands ###
